//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympicMedalists
    {
        public int ID { get; set; }
        public string city { get; set; }
        public Nullable<int> year { get; set; }
        public string sport { get; set; }
        public string discipline { get; set; }
        public string country { get; set; }
        public string gender { get; set; }
        public string @event { get; set; }
        public string eventGender { get; set; }
        public string color { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
    }
}
